"""CAM export for laser cutting (G-code generation)."""

from pathlib import Path
from typing import Dict, List, Optional
import numpy as np
import cv2

from replan.desktop.models import PageTab, SegmentedObject, DynamicCategory
from replan.desktop.io.vector_export import ContourExtractor, VectorPath


class GCodeExporter:
    """Exports vector paths as G-code for laser cutting."""
    
    def __init__(self, feed_rate: float = 1000.0, power: float = 100.0, 
                 travel_speed: float = 3000.0):
        """
        Initialize G-code exporter.
        
        Args:
            feed_rate: Cutting feed rate (mm/min)
            power: Laser power (0-100%)
            travel_speed: Travel speed for moves (mm/min)
        """
        self.feed_rate = feed_rate
        self.power = power
        self.travel_speed = travel_speed
        self.extractor = ContourExtractor()
    
    def export_page(self, path: str, page: PageTab,
                   categories: Dict[str, DynamicCategory],
                   scale_mm_per_pixel: float = 0.1) -> bool:
        """
        Export page as G-code.
        
        Args:
            path: Output file path
            page: Page to export
            categories: Category definitions
            scale_mm_per_pixel: Scale factor to convert pixels to mm
            
        Returns:
            True if successful
        """
        try:
            # Extract all vector paths
            paths = self.extractor.extract_from_page(page, categories)
            
            if not paths:
                return False
            
            # Generate G-code
            gcode_lines = self._generate_gcode(paths, scale_mm_per_pixel)
            
            # Write to file
            with open(path, 'w', encoding='utf-8') as f:
                f.write('\n'.join(gcode_lines))
            
            return True
        except Exception as e:
            print(f"Error exporting G-code: {e}")
            return False
    
    def _generate_gcode(self, paths: List[VectorPath], scale: float) -> List[str]:
        """Generate G-code from vector paths."""
        lines = []
        
        # Header
        lines.append("; G-code generated by RePlan")
        lines.append("; Laser cutting file")
        lines.append("")
        lines.append("G21 ; Set units to millimeters")
        lines.append("G90 ; Absolute positioning")
        lines.append("G28 ; Home all axes")
        lines.append("")
        
        # Group paths by category for efficient cutting
        paths_by_category = {}
        for path in paths:
            if path.category not in paths_by_category:
                paths_by_category[path.category] = []
            paths_by_category[path.category].append(path)
        
        # Process each category
        for category, category_paths in paths_by_category.items():
            lines.append(f"; Category: {category}")
            
            for path in category_paths:
                if len(path.contour) < 3:
                    continue
                
                # Move to start position (rapid)
                start_x, start_y = path.contour[0]
                x_mm = start_x * scale
                y_mm = start_y * scale
                lines.append(f"G0 X{x_mm:.3f} Y{y_mm:.3f} ; Rapid move to start")
                
                # Turn on laser
                lines.append(f"M3 S{int(self.power * 10)} ; Turn on laser at {self.power}%")
                
                # Cut along contour
                for point in path.contour[1:]:
                    x_mm = point[0] * scale
                    y_mm = point[1] * scale
                    lines.append(f"G1 X{x_mm:.3f} Y{y_mm:.3f} F{self.feed_rate} ; Cut")
                
                # Close contour if needed
                if path.is_outer:
                    lines.append(f"G1 X{start_x * scale:.3f} Y{start_y * scale:.3f} F{self.feed_rate} ; Close contour")
                
                # Turn off laser
                lines.append("M5 ; Turn off laser")
                lines.append("")
        
        # Footer
        lines.append("G28 ; Home all axes")
        lines.append("M30 ; End of program")
        
        return lines
